services:
  go-api:
    container_name: go-api
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - primeira-network-bridge

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=postgres 
    ports:
      - 5432:5432 
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - primeira-network-bridge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  primeira-network-bridge:
    name: primeira-network-bridge
    external: true
    driver: bridge

volumes:
  db:
