name: CI Pipeline

on:
  push:
    branches:
      - main

permissions: 
  id-token: write
  contents: write

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Golang 
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Configure Amazon AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::575108923772:role/ecr-role
          aws-region: us-east-1

      - name: AWS Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate tag based on commit hash
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build image and push
        env: 
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: | 
          docker build -t $REGISTRY/go-api:$TAG .
          docker push $REGISTRY/go-api:$TAG
