name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Golang 
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Generate tag based on commit hash
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build image and push
        env: 
          REGISTRY: matheustanaka
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: | 
          docker build -t $REGISTRY/go-api-connect-db:$TAG .
          docker push $REGISTRY/go-api-connect-db:$TAG
